# Server configuration
server.port=8082

# Application name
spring.application.name=BookApp

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Spring Security ? Basic Auth
spring.security.user.name=sahil12
spring.security.user.password=pass123

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Library
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging to file
logging.file.name=logs/bookapp.log

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
